# Generated by Django 3.0.4 on 2020-03-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(default='101', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='fullname',
            field=models.CharField(default='shreya', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(default='swqd', max_length=15),
            preserve_default=False,
        ),
    ]
